<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' => array(
    'InterpellerApplication' => 'interpeller/application/InterpellerApplication.php',
    'InterpellerBaseController' => 'interpeller/controller/InterpellerBaseController.php',
    'InterpellerGraphController' => 'interpeller/controller/InterpellerGraphController.php',
    'InterpellerGraphView' => 'interpeller/views/InterpellerGraphView.php',
    'KanbanApplication' => 'kanban/application/KanbanApplication.php',
    'KanbanController' => 'kanban/controller/KanbanController.php',
  ),
  'function' => array(),
  'xmap' => array(
    'InterpellerApplication' => 'PhabricatorApplication',
    'InterpellerBaseController' => 'PhabricatorController',
    'InterpellerGraphController' => 'InterpellerBaseController',
    'InterpellerGraphView' => 'AphrontView',
    'KanbanApplication' => 'PhabricatorApplication',
    'KanbanController' => 'PhabricatorController',
  ),
));
